### ISSUE TITLE
Reduce app bundle size

### ISSUE THREAD

**Issue by devsdevsdevs** [icssc/AntAlmanac#118]
Right now the bundle (which you can get by running `npm run build` inside the client directory) stands at ~6.8 MB. This is significantly smaller when g-zipped, but is still way too large and could be trimmed down. We should look into webpack minification customization, make sure tree shaking is working, and also figure out if we want to bundle images and other static files.

**Comment by EricPedley** [comment]
Closing because our bundle size has gone down. I'll still open another issue about removing static files from the bundle because I think it's easier to tackle that one area, but I don't think this is a huge deal because right now our bundle is already smaller. The larger problem is that the entire bundle needs to be loaded for the page to start loading but we don't need everything in there for the initial page load.
![image](https://user-images.githubusercontent.com/48658337/177025684-457b6c70-4c75-49e4-9f14-e19e6a2927ed.png)
See this article for details about reading the Chrome devtools network tab: https://developer.chrome.com/docs/devtools/network/reference/#total-size

I ran the `source-map-explorer` npm package on our project to generate the figure below (best viewed in new tab), and it looks like some of the biggest offenders for our bundle are static assets like the logos and building and department catalogs, which would be better loaded at runtime instead of bottlenecking the bundle download, but those would only net us about 50k less uncompressed, which is pretty much negligible:
![image](https://user-images.githubusercontent.com/48658337/177025340-85ca1da7-a42f-4612-855f-88161c7797e2.png)
