### ISSUE TITLE
"News" is not new at all

### ISSUE THREAD

**Issue by MinhxNguyen7** [icssc/AntAlmanac#472]
The News box seems to contain not very new information, with the most recent being from 11 months ago
![image](https://user-images.githubusercontent.com/64875104/216897235-f362ee37-91f7-4f19-8427-6225775ae0f9.png)
I can remove it if we want to do that. Also, maybe we should just automatically not display "news" that are more than a certain age.

**Comment by ap0nia** [comment]
My alpha branch implements infinite scrolling news; it'll always show the ~5 latest news on top, and you can infinitely load more items as you scroll down.

https://github.com/icssc/AntAlmanac/blob/aponia-monorepo/apps/client/src/components/Header/News.tsx

However, this doesn't address the concern of filtering for recent dates. Any thoughts? @MinhxNguyen7

**Comment by MinhxNguyen7** [comment]
@johnlorenzini is working to replace this with the patch notes modal I think. Having infinite scroll on patch notes could make sense.

**Comment by ap0nia** [comment]
This feature was inspired by the notification bell on YouTube; clicking on the bell opens a popup that can scroll infinitely (I don't have any notifications so it's empty).

<img width="1186" alt="image" src="https://user-images.githubusercontent.com/66761366/223581420-b5b726dc-1ebd-4c94-89a6-3d529fa4f5f6.png">

I don't think it makes much sense to implement this for the patch notes modal mainly because modals shouldn't be the primary way of displaying lot of info. Also, the infinite scroll exists as a way to browse previous news if the user is interested in viewing them, but the patch notes modal is currently intended to be hidden unless the user has never seen the modal before, defeating the purpose of being able to view the news at any time

**Comment by MinhxNguyen7** [comment]
I'm not that familiar with what the vision with the news/patch notes is. You'll just have to ask @johnlorenzini
