### ISSUE TITLE
Delineate day and schedule name in custom events modal

### ISSUE THREAD

**Issue by MinhxNguyen7** [icssc/AntAlmanac#520]
Right now, the days and schedules look like they're part of the same list. I think that there should be labels/headings to indicate the two. I think it would look better as well in addition to being quicker to parse.

![image](https://user-images.githubusercontent.com/64875104/222984710-7227608e-fbc5-438b-82c4-d878b88a64b1.png)

**Comment by ap0nia** [comment]
This is a screenshot my implementation of the form, what do you think?
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/66761366/223560031-100d0236-b251-4e9b-ae20-7e5751a229c0.png">

**Comment by MinhxNguyen7** [comment]
I think only a heading or dividing line is necessary, not both. That matters on mobile especially because of the limited space. On that note, you might want to check how it looks on mobile. Otherwise, it looks good and pretty clean 👍

**Comment by ap0nia** [comment]
It's not too bad; it overflows + scrolls, weird sizing, but legible at least.

<img width="386" alt="image" src="https://user-images.githubusercontent.com/66761366/223566420-3c54a7bb-fbb3-4d40-90cd-4b252a451722.png">

I don't like dealing with UI, much less mobile UI lol. But any feedback/concrete UI decisions are appreciated -- especially for the Alpha branch since I can do whatever I want there

**Comment by teresa-liang** [comment]
Maybe we can do something similar to how Zotcourse allows users to create a custom event:
![image](https://github.com/icssc/AntAlmanac/assets/83627792/87843baf-0543-4849-b4dc-d3e12a34f70c)

A lot of space seems to be saved by abbreviating the days of the week, so maybe by doing this, there won't be any overflowing or weird scrolling.
I can try to find a good way to implement this!

**Comment by MinhxNguyen7** [comment]
@teresa-liang That looks pretty good!

**Comment by teresa-liang** [comment]
Goal: finish in 2 weeks (10/19)
