### ISSUE TITLE
Sort by columns

### ISSUE THREAD

**Issue by MinhxNguyen7** [icssc/AntAlmanac#524]
<img width="635" alt="image" src="https://user-images.githubusercontent.com/64875104/223307292-c1093685-20e3-4b0b-bd57-bc5cd9b8d384.png">
(Above) ZotCourse sorting by enrolled count.

Part of #440

**Comment by ap0nia** [comment]
What's leaflet grid? The website is written with MUI, so ideally we'd use something natively offered by them:
https://mui.com/material-ui/react-table/#sorting-amp-selecting

MUI also has an advanced data table component that can be used instead of the basic one: 
https://mui.com/x/react-data-grid/

Tanstack table is a headless table (i.e. it'll  handle all the logic required for a table, but you bring your own table component) that you can investigate if you want complex data handling logic for the table:
https://tanstack.com/table/v8

Personally, I prefer handling data transformations on the server, e.g. sorting, filtering, etc. and defining a clear API to do that. The frontend would just need to send the corresponding query whenever its state changes.

**Comment by MinhxNguyen7** [comment]
Oops. I meant React Grid. I wrote this quickly while we were leaving the meeting and didn't check myself.

Server-side transformations make sense for filtering, but with ordering, people can switch it around by clicking once, so I think that would be a waste of bandwidth. The returned information is essentially the same. Then, I don't think that client-side caching on top of that would be a more elegant solution over the grid.

**Comment by ap0nia** [comment]
I definitely think that's valid because the app is primarily client-side driven. 

My main priority for this feature would be to sufficiently scale down the complexity of the sorting; e.g. abstracting it away as a function outside of the component. 

If complexity ever becomes an issue, I'd personally defer to server-side data handling because we can implement more sophisticated strategies without having to handle complex nested sorting on our side. 

...A caveat to the point above is the existence of [Fuse.js](https://fusejs.io/), which we can import into the React app to do the complex sorting/filtering/searching. The bundle size is already massive tho, so maybe not a good first choice :skull:

**Comment by MinhxNguyen7** [comment]
React Grid seems to have that built in from a cursory look. I'll have to look into it

**Comment by ap0nia** [comment]
Ultimately, you can learn and work with whatever you'd like so you can get experience with a variety of libraries. You can gain a lot of valuable experience by learning how different APIs work and how they choose to integrate themselves into the React ecosystem.

With respect to the concrete direction of the project, I'd recommend sticking to anything natively supported by MUI. Aside from handling themes, colors, etc. more consistently across the website,
my biggest reason for this is that I believe you implicitly sign a contract with the MUI gods that you will defer to them for ***any*** and ***all*** UI from thenceforth lol. Using external UI libraries breaks this contract, and in return they will break your legs :skull: (jk).

Some of my thought process on choosing libraries vs. alternatives, i.e. @silevis/reactgrid vs @tanstack/react-table
- reactgrid was last published 8 months ago, and explicitly supports up to React-16 (the goal is to eventually migrate to React-18)
- implied by the notes above, the styles and theming may not match the rest of the website and it's a generally a pain to apply extremely specific styles like MUI to a third party
- reactgrid has [700 GitHub stars](https://github.com/silevis/reactgrid) and [6K weekly downloads on NPM](https://www.npmjs.com/package/@silevis/reactgrid), vs. @tanstack/react-table which has [21K GitHub stars](https://github.com/tanstack/table) and [400K weekly downloads on NPM](https://www.npmjs.com/package/@tanstack/react-table)
- ^ I bring up tanstack because it's an extremely established namespace within JS land (e.g. you should undebatably be using [tanstack query](https://tanstack.com/query/latest/docs/react/overview) for ***all*** projects that have ***any*** API requests and server-side state requirements) and the table implementation is headless, meaning you can use your own components, e.g. MUI, to render the table.

Feel free to reach out on Discord if you wanna discuss more when you try out implementing this! This isn't meant to deter you from trying out different solutions; I just wanted to share some of my thought process when selecting libraries to use for projects.

**Comment by MinhxNguyen7** [comment]
Oh I think there's a misunderstanding. The "React Grid Component" is a [MUI component](https://mui.com/material-ui/react-grid/). It's closely related to the table component that we're using now. I didn't intend to add another dependency. 

Thanks for the advice though. I'll keep it in mind.

**Comment by MinhxNguyen7** [comment]
We decided to sort over all sections but still separate sections by courses with repeating course numbers. This means that the current code is completely useless, so I'm closing this.

**Comment by MinhxNguyen7** [comment]
We decided to sort over all sections but still separate sections by courses with repeating course numbers. This means that the current code is completely useless, so I'm closing this.

**Comment by KevinWu098** [comment]
Is this PR closable as not planned? IIRC a few weeks ago, we discussed it and concluded that sorting by columns doesn't have many, if any, use cases
