### ISSUE TITLE
Map locations don't update when changing schedules

### ISSUE THREAD

**Issue by MinhxNguyen7** [icssc/AntAlmanac#566]
See title.

## Reproduction

Have a profile with multiple schedules. Open the map. Change to another schedule.

## Issues
Possibly addressed by #563

**Comment by KevinWu098** [comment]
I've got this one 💖, just busy trying to understand what a Git branch and fork is before I submit my pull. _Personally, I prefer my utensils more spoon-like, but to each their own._

In the meantime, the fix is to change `this.state.getEventsInCalendar` to `AppStore.getEventsInCalendar()`. `this.state.getEventsInCalendar` appears twice in `UCIMap.tsx`, on the route generator and the marker display. Both do not change on schedule swap, so I sniped an extra bug with this one 😋.
