### ISSUE TITLE
Filter out major/school restrictions

### ISSUE THREAD

**Issue by MinhxNguyen7** [icssc/AntAlmanac#595]
This is especially useful when looking at GEs. This can be done on our side, but API should probably do this. It should be a pretty simple change on their side, but I'm not sure how we would implement it UI-wise

**Comment by EricPedley** [comment]
I just found myself wanting to have this feature planning my classes for next quarter. FYI, since the last actions on this issue (closing client-side PR in February this year, and moving this issue to backlog in April), the API side has implemented filtering: https://github.com/icssc/peterportal-api-next/pull/130 (merged in May this year)
