### ISSUE TITLE
Replace public mapbox token

### ISSUE THREAD

**Issue by EricPedley** [icssc/AntAlmanac#718]
Instead of having a public token, have a server that can proxy requests or something. We have about 20 days to do this 😳
![image](https://github.com/icssc/AntAlmanac/assets/48658337/d447edbe-ee07-4936-90cc-4d4e290e8088)

**Comment by EricPedley** [comment]
Turns out we exceeded the free tier because usage of the map spiked around the first day of classes.
![image](https://github.com/icssc/AntAlmanac/assets/48658337/542d2dc1-2b33-4406-aa8f-fa3429e0193f)

**Comment by ap0nia** [comment]
A (possibly) difficult issue to tackle is how we could minimize the number of map requests made for the routing (if at all possible). You can view the many, many requests made for routing if you open the network tab and repeatedly switch between the selected day.

<img width="926" alt="image" src="https://github.com/icssc/AntAlmanac/assets/66761366/cd102ea8-1394-4b80-802d-0d328fd292a7">

I'm not looking too closely at the map right now, but a big reason for why this occurs should be a result of how the data fetching of each route is tied to its rendering, i.e. the component fetches route data when its corresponding day is selected and rendered. It's possible that this isn't the root cause of the issue, but it could be something to consider in a followup.
