### ISSUE TITLE
Accessibility Feature

### ISSUE THREAD

**Issue by stevenguyukai** [icssc/AntAlmanac#859]
# Accessibility settings (More of a design side)

1. The color picker for the course will change to a certain color range for people who need it
2. Compatible for Screen Reader 
3. Font Re-size
4. Alternative Text for Images
5. Contrast Ratio

See Accessibility principles [here](https://www.w3.org/WAI/fundamentals/accessibility-principles/)

**Comment by MinhxNguyen7** [comment]
1. Not sure how you would implement that, but that sounds like a fine idea.
2. Are we not screen reader compatible? Can you elaborate on how we might do that?
3. The user can use `Ctrl +` to increase the size of elements. Is that not sufficient?
4. What images do we have? 
5. This is something that we've talked about a lot before about specific elements/sections, but we didn't figure out better solutions. What in particular do you think should be changed and (optionally) to what? 

Improving accessibility is a good idea, and, even though AA isn't bad, it's not that good in this front. That being said, I think this is a matter of "be the change you want to see" because I'm not sure anyone would want to take this on, at least not without concrete designs/instructions. If you can elaborate more on exactly what we need to do/can find someone to design, it'd be a bit tricky to do anything.

**Comment by stevenguyukai** [comment]
In my Safari Browser testing, the keyboard navigation could be more complete (sometimes it works fine, but sometimes it doesn't go as expected.) 

I ran a website checker called Lighthouse(An extension from Google I think). and the result for Antalmanac is :
<img width="1402" alt="image" src="https://github.com/icssc/AntAlmanac/assets/47913844/159276d9-0657-444f-87a0-93ba9fa91992">

So, Antalmanac's accessibility is great. But its performance isn't looking very good. So maybe accessibility is not the priority,  we should focus more on performance 🤔

**Comment by MinhxNguyen7** [comment]
That's simulated on shitty network I think, which is not invalid, but it's not representative. Do you find that it's slow? Page load only takes like a second for me, which is quite acceptable.

If it's actually a problem, then we should tackle it, but I don't see that's a problem right now. However, If you're interested in optimizing the page, then you should definitely do it. It'd be a good experience.

**Comment by stevenguyukai** [comment]
I think its not because the bad network:
<img width="1402" alt="image" src="https://github.com/icssc/AntAlmanac/assets/47913844/edc27958-8caa-4826-9de0-34ff7a6229a5">

There is a request that finishes around 5th second after initial page load. 
> FCP measures how long it takes the browser to render the first piece of DOM content after a user navigates to your page. Images, non-white <canvas> elements, and SVGs on your page are considered DOM content; anything inside an iframe isn't included.

And since google is using it to measure a website's performance, maybe we should look in to it. And maybe it will includes in a better SEO, let Antalmanac rank higher than ZotCourse 👊

Issue: [#957](https://github.com/icssc/AntAlmanac/issues/957)

**Comment by MinhxNguyen7** [comment]
If you'd like to open an issue about performance, go ahead. For now, I'll close this one since our accessibility is fine, as far as I can see.
