### ISSUE TITLE
AntAlmanac doesn't load on Mac Safari

### ISSUE THREAD

**Issue by calejvaldez** [icssc/AntAlmanac#946]
When my friend tries to load AntAlmanac, he gets a blank page. This is the only content that appears in the JavaScript console.

Device: MacBook Pro 13-inch M1 2020
OS: macOS 11.4 (Big Sur)

![image](https://github.com/icssc/AntAlmanac/assets/97059433/edaf4c21-1354-45a4-befd-31bd6ec47efd)

**Comment by MinhxNguyen7** [comment]
`structuredClone` has been supported in every major browser since March 2022, and Big Sur reached end-of-life November 2023. You should tell your friend to update his device and browser, not for AntAlmanac's sake, but for his own security.

I don't like blaming the user, but I think this is reasonable
