### ISSUE TITLE
GPA column doesn't work in added courses pane

### ISSUE THREAD

**Issue by MinhxNguyen7** [icssc/AntAlmanac#983]
## Description
- The GPA column is there but is always empty.
- When you search for the class in the search pane, the GPA column shows up properly.
- When you come back to the added pane, the number for that course is there.

### Diagnosis
- There is a parameter in the method that handles querying for courses which controls whether to only read from the cache or check upstream from the API.
    - This is so that the search pane can send a batch query to the API instead of the courses individually querying.
- The bug is most likely caused by the fact that the GPA API call is not triggered by a search, then the section table cells search the cache, finds nothing, and the query is not propagated to the API because that parameter is not toggled.
    - This should be fixable by simply by passing `true` into that parameter.
    - However, we should quickly check for query deduplication. I think I implemented something that stops duplicate queries when one is in-flight, but we should check.

**Comment by ap0nia** [comment]
This could be resolved by adjusting this line of code: https://github.com/icssc/AntAlmanac/blob/main/apps/antalmanac/src/components/RightPane/SectionTable/SectionTableBody.tsx#L221

The added courses tab is tab 1, which this condition specifically says to force cache only, and return null if the cache is missed.

**Comment by adcockdalton** [comment]
Getting some weirdness with this issue.

We are actually to set that parameter to false, though the default is true, since it sets cacheOnly as @ap0nia said.

This was accompanied by slight delay when I loaded it on localhost, but not so much to signal abnormality to me. Moreover, note that this is the exact function call that the grades popup memo employs, so if query deduplication is an issue, than it is already an issue in the current build.

~removing some artifacts from my testing~

Looking into it more now.

**Comment by adcockdalton** [comment]
![image](https://github.com/icssc/AntAlmanac/assets/105406853/80e15bfa-578b-4a88-9a63-6a202a666cb5)

Testing procedure:
- add distinct console statements before and after the only two instances of the function call queryGrades
- add console statements within queryGrades specifying if cache is hit or bypassed
- load schedule with only CS 147
- enter course added pane and observe that the cache is bypassed since it is the first query for CS 147 grade data ✅
- enter search pane and search CS 147 and observe that for all discussions / classes for CS 147 the cache is used ✅

Looks good to me. Will remove log statements and make a PR. Was as simple as setting the parameter on the line that @ap0nia mentioned to false.
